"use strict";

var controllerNames = [
  "addExternalModule",
  "addUserToGroup",
  "changeAdminStatus",
  "changeArchivedStatus",
  "changeBio",
  "changeBlockedStatus",
  "changeGroupImage",
  "changeNickname",
  "changeThreadColor",
  "changeThreadEmoji",
  "connectE2EE",
  "createNewGroup",
  "createPoll",
  "deleteMessage",
  "disconnectE2EE",
  "deleteThread",
  "downloadE2EEMedia",
  "editMessage",
  "forwardAttachment",
  "getAvatarUser",
  "getCurrentUserID",
  "getE2EEDeviceData",
  "getEmojiUrl",
  "getFriendsList",
  "getMessage",
  "getRegion",
  "getThreadHistory",
  "getThreadInfo",
  "getThreadList",
  "getThreadPictures",
  "getUserID",
  "getUserInfo",
  "handleMessageRequest",
  "listenMqtt",
  "logout",
  "markAsDelivered",
  "markAsRead",
  "markAsReadAll",
  "markAsSeen",
  "muteThread",
  "pinMessage",
  "refreshFb_dtsg",
  "removeUserFromGroup",
  "resolvePhotoUrl",
  "searchForThread",
  "searchStickers",
  "sendMediaE2EE",
  "sendMessage",
  "sendMessageMqtt",
  "sendMessageE2EE",
  "sendReactionE2EE",
  "sendTypingE2EE",
  "sendTypingIndicator",
  // "sendTypingIndicatorMqtt",
  "setMessageReaction",
  "setMessageReactionMqtt",
  "setTitle",
  "stopListenMqtt",
  "threadColors",
  "unsendMessageE2EE",
  "unsendMessage",
  "httpGet",
  "httpPost",
  "getThreadListDeprecated",
  "getThreadHistoryDeprecated",
  "getThreadInfoDeprecated"
];

module.exports = controllerNames.reduce(function (acc, name) {
  acc[name] = require("./" + name + ".js");
  return acc;
}, {});
